name: demo (Branch) App distribution
on:
  workflow_dispatch:
    inputs:
      relse_note:
        description: '출시 노트 작성해주세요.'
        required: true
        default: "헤헤"
        type: string

      choice_testers:
        description: '테스터 그룹을 선택하여주세요.'
        required: true
        default: 'dev-dev'
        type: choice
        options:
        - 하하하호호호
        - dev-dev


