name: App distribution (Branch)

on:
  workflow_dispatch:
    inputs:
      release_note:
        description: '출시 노트 작성해주세요.'
        required: true
        type: string

      choice_testers:
        description: '테스터 그룹을 선택하여주세요.'
        required: true
        default: 'wewoot-dev'
        type: choice
        options:
          - 사내테스트-그룹
          - wewoot-dev
          - Dogfooding

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: actions/setup-node@v1 # This is optional on linux and macOS
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Fetch credential file from secrets
        id: fetch_credential_file
        uses: timheuer/base64-to-file@v1
        with:
          encodedString: ${{ secrets.CREDENTIAL_FILE }}
          fileName: 'credential_file.json'

      - name: build release
        run: ./gradlew assembleDebug

      - name: Upload artifact to Firebase Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFile: credential_file.json
          groups: ${{ github.event.inputs.choice_testers }}
          releaseNotes: ${{ github.event.inputs.release_note }}
          file: app/build/outputs/apk/debug/app-debug.apk